<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'Usuario',
                'display_name_plural' => 'Usuarios',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-02 13:55:30',
                'updated_at' => '2023-10-10 19:34:25',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2021-06-02 13:55:30',
                'updated_at' => '2021-06-02 13:55:30',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Rol',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerRoleController',
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2021-06-02 13:55:31',
                'updated_at' => '2024-02-17 00:04:41',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'permissions',
                'slug' => 'permissions',
                'display_name_singular' => 'Permiso',
                'display_name_plural' => 'Permisos',
                'icon' => 'voyager-list',
                'model_name' => 'App\\Models\\Permission',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":"table_name","order_display_column":"table_name","order_direction":"asc","default_search_key":null}',
                'created_at' => '2022-05-24 11:21:20',
                'updated_at' => '2022-05-24 11:21:20',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'room_types',
                'slug' => 'room-types',
                'display_name_singular' => 'Tipo de habitación',
                'display_name_plural' => 'Tipos de habitación',
                'icon' => 'voyager-tag',
                'model_name' => 'App\\Models\\RoomType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-10 21:56:34',
                'updated_at' => '2023-10-10 22:07:45',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'room_accessories',
                'slug' => 'room-accessories',
                'display_name_singular' => 'Accesorio',
                'display_name_plural' => 'Accesorios',
                'icon' => 'voyager-puzzle',
                'model_name' => 'App\\Models\\RoomAccessory',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-10 22:11:18',
                'updated_at' => '2023-10-11 18:29:07',
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'product_types',
                'slug' => 'product-types',
                'display_name_singular' => 'Tipo de producto',
                'display_name_plural' => 'Tipos de productos',
                'icon' => 'fa fa-tags',
                'model_name' => 'App\\Models\\ProductType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2023-10-11 08:09:34',
                'updated_at' => '2023-10-11 08:09:34',
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'service_types',
                'slug' => 'service-types',
                'display_name_singular' => 'Tipo de servicio',
                'display_name_plural' => 'Tipos de servicios',
                'icon' => 'voyager-window-list',
                'model_name' => 'App\\Models\\ServiceType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2023-10-11 10:39:56',
                'updated_at' => '2023-10-11 10:39:56',
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'branch_offices',
                'slug' => 'branch-offices',
                'display_name_singular' => 'Sucursal',
                'display_name_plural' => 'Sucursales',
                'icon' => 'fa fa-building',
                'model_name' => 'App\\Models\\BranchOffice',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-11 11:03:37',
                'updated_at' => '2024-03-13 23:40:36',
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'people',
                'slug' => 'people',
                'display_name_singular' => 'Persona',
                'display_name_plural' => 'Personas',
                'icon' => 'voyager-people',
                'model_name' => 'App\\Models\\Person',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-11 11:27:50',
                'updated_at' => '2023-12-20 06:38:55',
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'products',
                'slug' => 'products',
                'display_name_singular' => 'Producto',
                'display_name_plural' => 'Productos',
                'icon' => 'fa fa-shopping-basket',
                'model_name' => 'App\\Models\\Product',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-11 11:40:34',
                'updated_at' => '2023-10-21 15:52:47',
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'rooms',
                'slug' => 'rooms',
                'display_name_singular' => 'Habitación',
                'display_name_plural' => 'Habitaciones',
                'icon' => 'fa fa-bed',
                'model_name' => 'App\\Models\\Room',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-11 12:11:42',
                'updated_at' => '2024-03-13 22:23:25',
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'suppliers',
                'slug' => 'suppliers',
                'display_name_singular' => 'Proveedor',
                'display_name_plural' => 'Proveedores',
                'icon' => 'voyager-person',
                'model_name' => 'App\\Models\\Supplier',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-10-11 12:31:08',
                'updated_at' => '2023-10-11 12:32:20',
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'countries',
                'slug' => 'countries',
                'display_name_singular' => 'País',
                'display_name_plural' => 'Paises',
                'icon' => 'voyager-world',
                'model_name' => 'App\\Models\\Country',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-11-08 22:20:56',
                'updated_at' => '2023-11-08 22:27:38',
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'states',
                'slug' => 'states',
                'display_name_singular' => 'Estado/Departamento',
                'display_name_plural' => 'Estados/Departamentos',
                'icon' => 'voyager-puzzle',
                'model_name' => 'App\\Models\\State',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-11-08 22:23:01',
                'updated_at' => '2023-11-08 22:32:28',
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'cities',
                'slug' => 'cities',
                'display_name_singular' => 'Ciudad',
                'display_name_plural' => 'Ciudades',
                'icon' => 'voyager-location',
                'model_name' => 'App\\Models\\City',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-11-08 22:24:58',
                'updated_at' => '2023-11-08 22:44:37',
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'penalty_types',
                'slug' => 'penalty-types',
                'display_name_singular' => 'Tipo de multa',
                'display_name_plural' => 'Tipo de multas',
                'icon' => 'voyager-warning',
                'model_name' => 'App\\Models\\PenaltyType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2023-11-19 18:58:32',
                'updated_at' => '2023-11-19 18:58:32',
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'jobs',
                'slug' => 'jobs',
                'display_name_singular' => 'Cargo',
                'display_name_plural' => 'Cargos',
                'icon' => 'voyager-list',
                'model_name' => 'App\\Models\\Job',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2023-12-11 21:44:53',
                'updated_at' => '2023-12-11 21:44:53',
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'employes',
                'slug' => 'employes',
                'display_name_singular' => 'Empleado',
                'display_name_plural' => 'Empleados',
                'icon' => 'voyager-person',
                'model_name' => 'App\\Models\\Employe',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-12-11 21:56:12',
                'updated_at' => '2023-12-11 21:58:51',
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'food_types',
                'slug' => 'food-types',
                'display_name_singular' => 'Refrigerio',
                'display_name_plural' => 'Refrigerios',
                'icon' => 'voyager-bread',
                'model_name' => 'App\\Models\\FoodType',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2023-12-19 18:23:19',
                'updated_at' => '2023-12-19 18:24:55',
            ),
        ));
        
        
    }
}